version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout 
      - run:
          name: Installing Packages
          command: pip install --user pyyaml jinja2 requests 

      - run:
          name: Building Dashboard
          command: |
            python make_status.py 
            mkdir -p deploy 
            mv status.html deploy/index.html
            cp static/style.css deploy/
            pwd && ls -ltr

      - store_artifacts:
          path: deploy/

      - persist_to_workspace:
          root: .
          paths: 
            - deploy/ 

  deploy-job:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - add_ssh_keys:
          fingerprints:
            - "kkd"
              
      - run:
          name: Copy over built site files
          command: rm -rf deploy && cp -r /tmp/workspace/deploy ../deploy 
      
      - run:
          name: Change to gh-pages branch and replace w/ new site
          command: |
            git checkout gh-pages
            rm -rf ./*
            cp -r ../deploy/* ./
            touch ./index.html

      - run:
          name: Commit results and push to gh-pages
          command: |
            git config --global user.email "abanihi@ucar.edu"
            git config --global user.name "Xdev Bot"
            git add -A
            git commit -m "Automated web deploy"
            git push -f origin gh-pages:gh-pages

workflows:
  version: 2
  default:
    jobs:
      - build-job:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only:
                - master
              ignore:
                - gh-pages
              